=== FranciscoFer99/Lenguaje-de-Marcas-Entrega/DTD2018/examen.dtd
<!ELEMENT coches (#PCDATA | modelo | combustible)*>
<!ELEMENT modelo EMPTY >
<!ATTLIST modelo nombre ID #REQUIRED
                    ruedas CDATA #IMPLIED
                    modelo CDATA #IMPLIED
                    motor CDATA #FIXED "1.9tdi">
<!ELEMENT combustible (electrico, (gasoleo | gasolina)*)>
<!ATTLIST combustible nombre ID #REQUIRED>
<!ELEMENT electrico (#PCDATA)>
<!ELEMENT gasoleo (#PCDATA)>
<!ELEMENT gasolina (#PCDATA)>

=== FranciscoFer99/Lenguaje-de-Marcas-Entrega/DTD2018/examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coches SYSTEM "examen.dtd">
<coches>
  Coches_Actuales
  <modelo nombre="Renault" modelo="Scenic" />
  <modelo nombre="Citröen" ruedas="Cuatro" />
  <modelo nombre="BMW" ruedas="Cuatro + Repuesto" />
  <modelo nombre="Suzuki" motor="1.9tdi" />
  <combustible nombre="Renault">
    <electrico>Si</electrico>
    <gasolina>Si</gasolina>
    <gasoleo>No</gasoleo>
  </combustible>
  <combustible nombre="Tesla">
    <electrico>Si</electrico>
    </combustible>
  </coches>
